import './globals.css'

export const metadata = {
  title: 'Servicios Willka',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  )
}
